[package]
name = "my-service-bus-macros"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = { version = "*", features = ["extra-traits"] }
quote = "*"


types-reader = { tag = "0.3.0", git = "https://github.com/MyJetTools/types-reader.git" }
